language: node_js
node_js:
  - "node"
  - "stable"
cache: yarn

jobs:
  include:
    - stage: deploy
      env: DEPLOY=netlify
      cache: yarn
      script: "npm --prefix web run build"
      before_deploy: "npm i -g netlify-cli" # can't use yarn global?!
      deploy:
        provider: script
        skip_cleanup: true
        script: "netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p web/build"
