[build]
  base    = "web"
  publish = "web/build"
  command = "yarn build"

[[redirects]]
  from = "https://masterpassx.cretezy.com/*"
  to = "https://masterpassx.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://masterpassx.netlify.com/*"
  to = "https://masterpassx.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.masterpassx.org/*"
  to = "https://masterpassx.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.cloudfront.net"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
