[build]
  base    = "web"
  publish = "web/build"
  command = "yarn build"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.cloudfront.net"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
